public:
    resource: "@PublicBundle/Resources/config/routing.yml"
    prefix:   /

manager:
    resource: "@ManagerBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
