djib_list:
    path:     /admin/djib/
    defaults: { _controller: ManagerBundle:Djib:index }

djib_add:
    path :    /admin/djib/add/
    defaults: { _controller: ManagerBundle:Djib:add}

djib_new:
    path : /admin/djib/new
    defaults : { _controller: ManagerBundle:Djib:create}
    requirements : { _methods: "post" } #POST, Post ?
